#pragma once

// Voxel context id
#define HCP_CONTEXT_VOXEL_MATRIX 1000
#define HCP_CONTEXT_POINT_CLOUD	 1100

// Voxel value id
#define HCP_VOXEL_MATRIX_VALUE     0
#define HCP_VOXEL_MATRIX_OPERATOR  1

// Voxel functions
#define HCP_VOXEL_FUNCTION_ENTITY      1


#define HCP_VOXEL_FUNCTION_TRANSLATION 100
#define HCP_VOXEL_FUNCTION_INTERACTION 200
